### ISSUE TITLE
Get rid of D5

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/ic880a-backplane#22]
The diode is not necessary when choosing the P-FET correctly:

https://www.youtube.com/watch?v=IrB-FPcv1Dc

**Comment by ubruhin** [comment]
D5 does *not* have the same functionality as the diode shown in the video. Our diode is for transient voltage suppression, not for Vgs overvoltage protection.

**Comment by dbrgn** [comment]
Oops, you're right. Thanks for noting, it's a bit late :smile:
